# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  appserver:
    image: appserver
    build:
      context: .
      dockerfile: App.Server/Dockerfile
    ports:
      - 5012:5012
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
